export const councils = {
	"Alcobendas": "@ALCBDS_Ayto",
	"Alcorcón": "@AytoAlcorcon",
	"Algete": "@AytoDeAlgete",
	"Arganda del Rey": "@Arganda_Ayto",
	"Becerril de la Sierra": "@BecerrilSierra",
	"Boadilla del Monte": "@Ayto_Boadilla",
	"Buitrago del Lozoya": "@AytoBuitrago",
	"Brunete": "@AytoBrunete",
	"Cercedilla": "@AytoCercedilla",
	"Collado Villalba": "@AyuntamientoCV",
	"Colmenarejo": "@ColmenarejoAyto",
	"El Molar": "@AytoElMolar",
	"Fresno de Torote": "@FresnoDeTorote",
	"Fuenlabrada": "@AytoFuenlabrada",
	"Galapagar": "@AytoGalapagar",
	"Getafe": "@AytoGetafe",
	"Guadarrama": "@Ayto_Guadarrama",
	"Horcajo de la Sierra-Aoslos": "@HorcajoAoslos",
	"Hoyo de Manzanares": "@Ayto_Hoyo",
	"Las Rozas de Madrid": "@Ayto_Las_Rozas",
	"Leganés": "@AytoLeganes",
	"Loeches": "@AytoDeLoeches",
	"Madrid": "@Madrid",
	"Meco": "@AytoMeco",
	"Morata de Tajuña": "@Ayto_Morata",
	"Navacerrada": "@AytoNavacerrada",
	"Pozuelo de Alarcón": "@Ayto_Pozuelo",
	"Parla": "@AytoParla",
	"San Agustín del Guadalix": "@AytoSanAgustin",
	"Torrelodones": "@Ayto_Torre",
	"Tres Cantos": "@Ayto3Cantos",
	"Valdeolmos-Alalpardo": "@Alalpardo_Ayto",
	"Villaviciosa de Odón": "@AytoVillaDeOdon",

	//No twitter account
	"Gargantilla del Lozoya y Pinilla de Buitrago": "#GargantillaDelLozoya y #PinillaDeBuitrago",
	"La Acebeda": "#LaAcebeda",
	"Navas del Rey": "#NavasDelRey",
	"Olmeda de las Fuentes": "#OlmedaDeLasFuentes",
	"Quijorna": "#Quijorna",
	"Santorcaz": "#Santorcaz",
	"Villamanrique de Tajo": "#VillamanriqueDeTajo",
	"Villamantilla": "#Villamantilla",
	"Villanueva de Perales": "#VillanuevaDePerales",

	// TODO: find account
	"Batres": "#Batres",
	"Coslada": "#Coslada",
	"Humanes de Madrid": "#Humanes",
	"Valdemoro": "#Valdemoro",
	"Robledo de Chavela": "#RobledoDeChavela",
	"San Fernando de Henares": "#SanFernandoDeHenares",
	"San Sebastián de los Reyes": "#SanSebastiánDeLosReyes",
	"Villa de Ajalvir": "#VillaDeAjalvir",
};
