export const councils = {
	"Alameda del Valle": "@AytAlamedaValle",
	"Alcalá de Henares": "@AytoAlcalaH",
	"Alcobendas": "@ALCBDS_Ayto",
	"Alcorcón": "@AytoAlcorcon",
	"Aldea del Fresno": "@AldeaDelFresno1",
	"Algete": "@AytoDeAlgete",
	"Alpedrete": "@AlpedreteAyto",
	"Aranjuez": "@Ayto_Aranjuez",
	"Arganda del Rey": "@Arganda_Ayto",
	"Arroyomolinos": "@Arroyomolinos",
	"Becerril de la Sierra": "@BecerrilSierra",
	"Boadilla del Monte": "@Ayto_Boadilla",
	"Brunete": "@AytoBrunete",
	"Buitrago del Lozoya": "@AytoBuitrago",
	"Casarrubuelos": "@AytoCasarru",
	"Cercedilla": "@AytoCercedilla",
	"Chapinería": "@AytoChapineria",
	"Ciempozuelos": "@AytCiempozuelos",
	"Cobeña": "@AytoCobena",
	"Collado Mediano": "@Ayto_CMediano",
	"Collado Villalba": "@AyuntamientoCV",
	"Colmenar Viejo": "@AytoColmenar",
	"Colmenarejo": "@ColmenarejoAyto",
	"Coslada": "@Ayto_Coslada",
	"Cubas de la Sagra": "@AytoCubas",
	"Daganzo de Arriba": "@Ayto_Daganzo",
	"El Álamo": "@AytoElAlamo",
	"El Escorial": "@AytoEscorial",
	"El Molar": "@AytoElMolar",
	"Fresno de Torote": "@FresnoDeTorote",
	"Fuenlabrada": "@AytoFuenlabrada",
	"Fuente el Saz de Jarama": "@AytoFuentElSaz",
	"Galapagar": "@AytoGalapagar",
	"Getafe": "@AytoGetafe",
	"Guadalix de la Sierra": "@AytoGuadalix",
	"Guadarrama": "@Ayto_Guadarrama",
	"Horcajo de la Sierra-Aoslos": "@HorcajoAoslos",
	"Hoyo de Manzanares": "@Ayto_Hoyo",
	"Humanes de Madrid": "@AytHumanes",
	"Las Rozas de Madrid": "@Ayto_Las_Rozas",
	"Leganés": "@AytoLeganes",
	"Loeches": "@AytoDeLoeches",
	"Los Molinos": "@AytoLosMolinos",
	"Lozoya": "@AytoBuitrago",
	"Madrid": "@Madrid",
	"Majadahonda": "@MajadahondaAyto",
	"Mancomunidad del Noroeste para la Gestión y el Tratamiento de los Residuos Urbanos": "@m_delnoroeste",
	"Mancomunidad Sierra del Rincón": "@MDSierraRincon",
	"Manzanares el Real": "@ManzanaresReal",
	"Meco": "@AytoMeco",
	"Miraflores de la Sierra": "@AytoMiraflores",
	"Morata de Tajuña": "@Ayto_Morata",
	"Móstoles": "@AytoMostoles",
	"Navacerrada": "@AytoNavacerrada",
	"Navalafuente": "@Ay_Navalafuente",
	"Navalagamella": "@Navalagamella_A",
	"Navalcarnero": "@Ayto_Naval",
	"Nuevo Baztán": "@AytoNuevoBaztan",
	"Paracuellos de Jarama": "@AytoParacuellos",
	"Parla": "@AytoParla",
	"Pelayos de la Presa": "@PelayosPresa",
	"Pinto": "@AytoPinto",
	"Pozuelo de Alarcón": "@Ayto_Pozuelo",
	"Puentes Viejas": "@PuentesViejas",
	"Rivas-Vaciamadrid": "@AytoRivas",
	"San Agustín del Guadalix": "@AytoSanAgustin",
	"San Fernando de Henares": "@Ayto_SFH",
	"San Lorenzo de El Escorial": "@aytosanlorenzo",
	"San Martín de la Vega": "@Ayto_SMV",
	"San Sebastián de los Reyes": "@SanseComunica",
	"Torrejón de Ardoz": "@Ayto_Torrejon",
	"Torrejón de la Calzada": "@ayto_calzada",
	"Torrelaguna": "@AytoTorrelagun",
	"Torrelodones": "@Ayto_Torre",
	"Torres de la Alameda": "@Ayto_Torres",
	"Tres Cantos": "@Ayto3Cantos",
	"Valdemorillo": "@AytValdemorillo",
	"Valdemoro": "@Ayto_Valdemoro",
	"Valdeolmos-Alalpardo": "@Alalpardo_Ayto",
	"Valdilecha": "@AytoValdilecha",
	"Velilla de San Antonio": "@AytoVelilla",
	"Venturada": "@Ayto_Venturada",
	"Villa de Ajalvir": "@AAjalvir",
	"Villa del Prado": "@AytoVillaDPrado",
	"Villanueva del Pardillo": "@AytoVvaPardillo",
	"Villar del Olmo": "@AyVillarDelOlmo",
	"Villaviciosa de Odón": "@AytoVillaDeOdon",
	"Zarzalejo": "@AytoZarzalejo",
	//No twitter account
	"Batres": "#Batres",
	"Belmonte de Tajo": "#BelmonteDeTajo",
	"Berzosa del Lozoya": "#BerzosaDelLozoya",
	"Bustarviejo": "#Bustarviejo",
	"Canencia": "#Canencia",
	"Carabaña": "#Carabaña",
	"Corpa": "#Corpa",
	"Estremera": "#Estremera",
	"Fuentidueña de Tajo": "#FuentidueñaDeTajo",
	"Gargantilla del Lozoya y Pinilla de Buitrago": "#GargantillaDelLozoya y #PinillaDeBuitrago",
	"Griñón": "#Griñón",
	"La Acebeda": "#LaAcebeda",
	"Los Santos de la Humosa": "#LosSantosDeLaHumosa",
	"Lozoyuela-Navas-Sieteiglesias": "#Lozoyuela #Navas #Sieteiglesias",
	"Mancomunidad de Servicios de Arquitectura y Urbanismo de la Sierra Norte": "#MSAU",
	"Mancomunidad de Servicios Los Olmos": "#MancomunidadServiciosLosOlmos",
	"Mancomunidad de Servicios Sociales Mejorada-Velilla": "#SSMejoradaVelilla",
	"Mejorada del Campo": "#MejoradaDelCampo",
	"Navas del Rey": "#NavasDelRey",
	"Olmeda de las Fuentes": "#OlmedaDeLasFuentes",
	"Orusco de Tajuña": "#OruscoDeTajuña",
	"Puebla de la Sierra": "#PueblaDeLaSierra",
	"Pinilla del Valle": "#PinillaDelValle",
	"Pozuelo del Rey": "#PozueloDelRey",
	"Quijorna": "#Quijorna",
	"Robledo de Chavela": "#RobledoDeChavela",
	"San Martín de Valdeiglesias": "#SanMartínDeValdeiglesias",
	"Santa María de la Alameda": "#SantaMaríaDeLaAlameda",
	"Santorcaz": "#Santorcaz",
	"Serranillos del Valle": "#SerranillosDelValle",
	"Titulcia": "#Titulcia",
	"Valdemaqueda": "#Valdemaqueda",
	"Villamanrique de Tajo": "#VillamanriqueDeTajo",
	"Villamantilla": "#Villamantilla",
	"Villanueva de la Cañada": "VillanuevaDeLaCañada",
	"Villanueva de Perales": "#VillanuevaDePerales",
	"Villarejo de Salvanés": "#VillarejoDeSalvanés",
	"Villavieja del Lozoya": "#VillaviejaDelLozoya",
};

